import { RFValue } from "react-native-responsive-fontsize";

export const FontFamily = {
  regular: 'PlusJakartaSans',
  medium: 'PlusJakartaSansMedium',
  bold: 'PlusJakartaSansBold',
  extraBold: 'PlusJakartaSansExtraBold',
  display: 'GudlaRegular',
  displayExtraBold: 'GudlaExtraBold',
};

export const fontScale = (size: number) => RFValue(size);

export const FontSize = {
  fourHalf: RFValue(4.5),
  five: RFValue(5),
  fiveHalf: RFValue(5.5),
  six: RFValue(6),
  sixHalf: RFValue(6.5),
  sixPointEight: RFValue(6.8),
  seven: RFValue(7),
  sevenHalf: RFValue(7.5),
  eight: RFValue(8),
  eightHalf: RFValue(8.5),
  nine: RFValue(9),
  ninePointTwo: RFValue(9.2),
  nineHalf: RFValue(9.5),
  ten: RFValue(10),
  tenHalf: RFValue(10.5),
  eleven: RFValue(11),
  twelve: RFValue(12),
  twelveHalf: RFValue(12.5),
  thirteen: RFValue(13),
  thirteenHalf: RFValue(13.5),
  fourteen: RFValue(14),
  fourteenHalf: RFValue(14.5),
  fifteen: RFValue(15),
  sixteen: RFValue(16),
  seventeen: RFValue(17),
  eighteen: RFValue(18),
  nineteen: RFValue(19),
  twenty: RFValue(20),
  twentyOne: RFValue(21),
  twentyTwo: RFValue(22),
  twentyThree: RFValue(23),
  twentyFour: RFValue(24),
  twentyFive: RFValue(25),
  twentySix: RFValue(26),
  twentySeven: RFValue(27),
  twentyEight: RFValue(28),
  twentyNine: RFValue(29),
  thirty: RFValue(30),
  thirtyOne: RFValue(31),
  thirtyTwo: RFValue(32),
  thirtyFour: RFValue(34),
  thirtySix: RFValue(36),
  thirtyEight: RFValue(38),
  thirtyNine: RFValue(39),
  forty: RFValue(40),
  fiftyTwo: RFValue(52),
  small: RFValue(12),
  body: RFValue(16),
  title: RFValue(18),
  heading: RFValue(23),
  fourten: RFValue(14),
};
