import type { UserRole } from './auth.types';

export interface User {
  id: number | string;
  name: string;
  role: UserRole;
  activated? : string | boolean;
  activated_at? : string;
  avatar? : string | null;
  banner?: string | null;
  bio?: string | null;
  created_at?: string;
  email: string;
  handle: string;
  location?: string | null;
  country_code?: string | null;
  country?: string | null;
  currency?: string | null;
  phone?: string | null;
  total_followers?: number;
  total_subscribers?: number;
  total_likes?: number;
  vibes?: string[];
  updated_at?: string;
  verified?: boolean;
  verified_at?: string;
}

export type Gender = 'male' | 'female';

export type UpdateProfilePayload = {
  name?: string;
  username?: string;
  bio?: string | null;
  phone?: string | null;
  dob?: string | null;
  gender?: Gender | null;
  location?: string | null;
  country_code?: string | null;
};

export type AvatarUploadSource = {
  uri: string;
  name?: string;
  type?: string;
};

export type RootStackParamList = {
  Splash: undefined;
  MainTabs: Record<string, unknown> | undefined;
  GetStarted: undefined;
  Login: undefined;
  EmailPhone: { isCreateAccount?: boolean } | undefined;
  EmailVerification: Record<string, unknown> | undefined;
  VerifyOtp: Record<string, unknown> | undefined;
  ForgotPassword: undefined;
  ResetPassword: Record<string, unknown> | undefined;
  TermsPolicies: { onboarding?: boolean; nextRoute?: keyof RootStackParamList } | undefined;
  PrivacyCentre: undefined;
  VibePicker: { firstSignIn?: boolean } | undefined;
  Chat: Record<string, unknown> | undefined;
  Settings: Record<string, unknown> | undefined;
  MembershipTiers: Record<string, unknown> | undefined;
  ArtistProfile: Record<string, unknown> | undefined;
  UploadContent: Record<string, unknown> | undefined;
  FanSettings: Record<string, unknown> | undefined;
  GoLive: Record<string, unknown> | undefined;
  CreatorEvents: Record<string, unknown> | undefined;
  CreatorAnalytics: Record<string, unknown> | undefined;
  CreatorRevenue: Record<string, unknown> | undefined;
  FanSubscriptions: Record<string, unknown> | undefined;
  Community: Record<string, unknown> | undefined;
  Analytics: Record<string, unknown> | undefined;
  Subscribers: Record<string, unknown> | undefined;
  Challenges: Record<string, unknown> | undefined;
  RecordContent: Record<string, unknown> | undefined;
  CreateContent: Record<string, unknown> | undefined;
  CreatorLiveStream: Record<string, unknown> | undefined;
  CreatorBattleScreen: Record<string, unknown> | undefined;
  CreatorBattleParticipantScreen: Record<string, unknown> | undefined;
  LiveStream: Record<string, unknown> | undefined;
  StreamEnded: Record<string, unknown> | undefined;
  CreateChallenge: Record<string, unknown> | undefined;
  ChallengeDrafts: Record<string, unknown> | undefined;
  RevenueSplit: Record<string, unknown> | undefined;
  NoReward: Record<string, unknown> | undefined;
  RewardConfig: Record<string, unknown> | undefined;
  Reward: Record<string, unknown> | undefined;
  finalStep: Record<string, unknown> | undefined;
  challengeParticipants: Record<string, unknown> | undefined;
  ChallengeFeed: Record<string, unknown> | undefined;
  Vote: Record<string, unknown> | undefined;
  Video: Record<string, unknown> | undefined;
  EventDetail: Record<string, unknown> | undefined;
  SelectTickets: Record<string, unknown> | undefined;
  TicketVerification: Record<string, unknown> | undefined;
  ChallengeEntry: Record<string, unknown> | undefined;
  Library: Record<string, unknown> | undefined;
  EditSubmission: Record<string, unknown> | undefined;
  SubmitEntry: Record<string, unknown> | undefined;
  Livefeed: Record<string, unknown> | undefined;
  ConnectHub: Record<string, unknown> | undefined;
  Notification: Record<string, unknown> | undefined;
  StreakReward: Record<string, unknown> | undefined;
  ClaimPrize: Record<string, unknown> | undefined;
  CommunityPost: Record<string, unknown> | undefined;
  CommunityPostDetail: Record<string, unknown> | undefined;
  MarketPlace: Record<string, unknown> | undefined;
  UseSound: Record<string, unknown> | undefined;
  UseEffect: Record<string, unknown> | undefined;
  FanTicket: Record<string, unknown> | undefined;
  TopUpCoins: Record<string, unknown> | undefined;
  ChallengeLeaderboard: Record<string, unknown> | undefined;
  Events: Record<string, unknown> | undefined;
  TrendingVideos: Record<string, unknown> | undefined;
  Search: Record<string, unknown> | undefined;
  Submissions: Record<string, unknown> | undefined;
  Premium: Record<string, unknown> | undefined;
  VideoPlayer: Record<string, unknown> | undefined;
  PlaylistPlayer: Record<string, unknown> | undefined;
  HelpCentre: Record<string, unknown> | undefined;
  VibeSignature: Record<string, unknown> | undefined;
};

export type StoredUser = User | null;
